### PR TITLE
Fix graph layout on graph data update

### PR DESCRIPTION
**Pull request by nmbradford**
Resolves issue redefining elements causing specified layout style to not be applied.
Minor documentation updates to include how to get reference to cytoscape instance created within template from component code.

### CODE REVIEW

**Comment by dannyandersen** [comment]
Is there any reason this PR has not been merged?

**Comment by tonisbones** [comment]
Could someone merge these changes in? I'm hitting the issue where the layout isn't applying with new data so the nodes are all stacked on top of one another.

**Comment by tonisbones** [comment]
Note: I added the changes from https://github.com/calvinvette/ngx-cytoscape/pull/1/commits/04b6524db5c981481509100b485b8a65efc1fa0e to my local setup and it works. Cytoscape is weird and makes you rerun the layout when you add new elements.

**Comment by AdriaanSwan** [comment]
+1, bump, etc. to have this PR merged.

**Comment by calvinvette** [comment]
Never saw the notifications that a pull request was made - sorry for that. Reviewed & Merged. Will undo nmb- prefixes for consistency shortly.

**Pull request merged**
